// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5I7i7hLNqW8izhlgRnY3essRnBhg9BR0',
    appId: '1:1063051598461:web:7ee16c098571419949af14',
    messagingSenderId: '1063051598461',
    projectId: 'weight-tracker-app-7f04f',
    authDomain: 'weight-tracker-app-7f04f.firebaseapp.com',
    storageBucket: 'weight-tracker-app-7f04f.firebasestorage.app',
    measurementId: 'G-9MTNTD2QGP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkrLKZWEcpeXE2VwPaZ1530QTT-tobQvM',
    appId: '1:1063051598461:android:f1164accc425b6b549af14',
    messagingSenderId: '1063051598461',
    projectId: 'weight-tracker-app-7f04f',
    storageBucket: 'weight-tracker-app-7f04f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3QrU18BN3aUKsIqBwgNgGfEDcvFzVlpQ',
    appId: '1:1063051598461:ios:266181e652ba520149af14',
    messagingSenderId: '1063051598461',
    projectId: 'weight-tracker-app-7f04f',
    storageBucket: 'weight-tracker-app-7f04f.firebasestorage.app',
    iosBundleId: 'com.example.weightTrackerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3QrU18BN3aUKsIqBwgNgGfEDcvFzVlpQ',
    appId: '1:1063051598461:ios:266181e652ba520149af14',
    messagingSenderId: '1063051598461',
    projectId: 'weight-tracker-app-7f04f',
    storageBucket: 'weight-tracker-app-7f04f.firebasestorage.app',
    iosBundleId: 'com.example.weightTrackerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5I7i7hLNqW8izhlgRnY3essRnBhg9BR0',
    appId: '1:1063051598461:web:7d7a628b1d25052649af14',
    messagingSenderId: '1063051598461',
    projectId: 'weight-tracker-app-7f04f',
    authDomain: 'weight-tracker-app-7f04f.firebaseapp.com',
    storageBucket: 'weight-tracker-app-7f04f.firebasestorage.app',
    measurementId: 'G-MFERH6H1JT',
  );

}